# Generated by Django 5.0.2 on 2024-03-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_year_birth_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='year_birth',
            new_name='Income',
        ),
        migrations.AddField(
            model_name='user',
            name='Dt_Customer',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Education',
            field=models.CharField(blank=True, choices=[('Graduation', 'Graduation'), ('PhD', 'PhD'), ('Master', 'Master'), ('Basic', 'Basic'), ('2n Cycle', '2n Cycle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='MntFishProducts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='MntFruits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='MntGoldProds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='MntMeatProducts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='MntSweetProducts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='MntWines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='NumDealsPurchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Year_Birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
