# Generated by Django 5.0.2 on 2024-03-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_year_birth_user_income_user_dt_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Together', 'Together'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Alone', 'Alone'), ('Absurd', 'Absurd'), ('YOLO', 'YOLO')], max_length=20, null=True),
        ),
    ]
