# Generated by Django 5.0.2 on 2024-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_product_user_product_name_user_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
