# Generated by Django 5.0.2 on 2024-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_products_user_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.product'),
        ),
    ]
